/** Maghreb shipping destinations — cities selectable in Settings → Shipping. */

export const SHIPPING_COUNTRIES = [
  {
    code: "MA",
    name: "Morocco",
    cities: [
      "Casablanca",
      "Rabat",
      "Marrakech",
      "Fes",
      "Tangier",
      "Agadir",
      "Meknes",
      "Oujda",
      "Kenitra",
      "Tetouan",
      "Safi",
      "Mohammedia",
      "Khouribga",
      "El Jadida",
      "Beni Mellal",
      "Nador",
      "Taza",
      "Settat",
      "Larache",
      "Ksar El Kebir",
      "Sale",
      "Temara",
      "Khemisset",
      "Berrechid",
      "Khenifra",
      "Errachidia",
      "Essaouira",
      "Ouarzazate",
      "Dakhla",
      "Laayoune",
      "Guelmim",
      "Tiznit",
      "Inezgane",
      "Ait Melloul",
      "Taroudant",
      "Sidi Slimane",
      "Sidi Kacem",
      "Youssoufia",
      "Midelt",
      "Azrou",
      "Ifrane",
      "Chefchaouen",
      "Al Hoceima",
      "Fnideq",
      "Martil",
      "Berkane",
      "Taourirt",
      "Guercif",
      "Fquih Ben Salah",
      "Sidi Bennour",
    ],
  },
  {
    code: "DZ",
    name: "Algeria",
    cities: [
      "Algiers",
      "Oran",
      "Constantine",
      "Annaba",
      "Blida",
      "Batna",
      "Setif",
      "Djelfa",
      "Sidi Bel Abbes",
      "Biskra",
      "Tebessa",
      "El Oued",
      "Skikda",
      "Tiaret",
      "Bejaia",
      "Tlemcen",
      "Ouargla",
      "Bechar",
      "Mostaganem",
      "Bordj Bou Arreridj",
      "Chlef",
      "Souk Ahras",
      "Mascara",
      "El Eulma",
      "Tizi Ouzou",
      "Jijel",
      "Relizane",
      "Saida",
      "Guelma",
      "Laghouat",
      "Ain Defla",
      "Mila",
      "Bouira",
      "Tipaza",
      "Ain Temouchent",
    ],
  },
  {
    code: "TN",
    name: "Tunisia",
    cities: [
      "Tunis",
      "Sfax",
      "Sousse",
      "Kairouan",
      "Bizerte",
      "Gabes",
      "Ariana",
      "Gafsa",
      "Monastir",
      "Ben Arous",
      "Kasserine",
      "Medenine",
      "Nabeul",
      "Tataouine",
      "Beja",
      "Jendouba",
      "Mahdia",
      "Sidi Bouzid",
      "Tozeur",
      "Kebili",
      "Zaghouan",
      "Siliana",
      "Manouba",
      "Le Kef",
      "Hammamet",
      "Djerba",
      "La Marsa",
      "Carthage",
      "Nabeul Hammamet",
      "Zarzis",
    ],
  },
  {
    code: "EG",
    name: "Egypt",
    cities: [
      "Cairo",
      "Alexandria",
      "Giza",
      "Shubra El Kheima",
      "Port Said",
      "Suez",
      "Mansoura",
      "Tanta",
      "Asyut",
      "Ismailia",
      "Faiyum",
      "Zagazig",
      "Damietta",
      "Aswan",
      "Minya",
      "Damanhur",
      "Beni Suef",
      "Qena",
      "Sohag",
      "Hurghada",
      "Luxor",
      "6th of October",
      "Sharm El Sheikh",
      "New Cairo",
    ],
  },
] as const;

export type ShippingCountryCode = (typeof SHIPPING_COUNTRIES)[number]["code"];

/** Flat list of every selectable shipping city. */
export const ALL_SHIPPING_CITIES: string[] = SHIPPING_COUNTRIES.flatMap((c) => [
  ...c.cities,
]);

/** @deprecated Prefer ALL_SHIPPING_CITIES / SHIPPING_COUNTRIES — kept for Morocco defaults. */
export const MOROCCO_CITIES = SHIPPING_COUNTRIES[0].cities;

export const STORE_LANGUAGES = [
  { value: "en", label: "English" },
  { value: "ar", label: "Arabic" },
  { value: "fr", label: "French" },
] as const;

export type StoreLanguage = (typeof STORE_LANGUAGES)[number]["value"];
