/** Re-exports shipping destinations + store languages (legacy import path). */
export {
  ALL_SHIPPING_CITIES,
  MOROCCO_CITIES,
  SHIPPING_COUNTRIES,
  SHIPPING_REGIONS,
  STORE_LANGUAGES,
  countryCodeToName,
  findCountryCodeByName,
  findCountryCodeForCity,
  getCitiesForCountry,
  getCountriesForRegion,
  getCountryByCode,
  resolveCountryCode,
  type ShippingCountry,
  type ShippingCountryCode,
  type ShippingRegion,
  type ShippingRegionId,
  type StoreLanguage,
} from "@/lib/shipping-destinations";
