/** Auto-generated by scripts/optimize-theme-github-assets.mjs */
export const THEME_BLUR_DATA: Record<string, string> = {
  "minimal-preview": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoMAAkAA4BaJZwAApyZpLiQAP7uP4k/l56+IPOd/x9P/klovlwI5x2qSNn6OApnfpHpeRd9KUFjpKmyWdrKAAAA",
  "minimal-hero": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAkAA4BaJaQAAp2ryswAAP7rvPyRvSHoGrqvTw9HGIojjzL314cx166LSDKmLi+SWMFGFyzAAAAA",
  "modern-preview": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACQAQCdASoMAAkAA4BaJaQAAltB1gAA/vcRbDDHuuobh2YuH3J3NX92g7qJkq/Jlks45n+EAAA=",
  "modern-hero": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoMAAkAA4BaJaQAAuzXxOv0NwAA/vc+nag/6S4rcatKehgwTm0R0F3upnfzXi37D12I5Tv4HiTOQ7tlj+l3reAxsm8XYgAA",
  "bold-preview": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAkAA4BaJQBOgCIfOCsYwAD973orhZMOrTDW20G95F2UiLfNra5XYKjlb53sby7rbm2ggp6cVy675FIAAA==",
  "bold-hero": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoMAAkAA4BaJZwAAujbaG8AAP73CKJ9OIgOqdFaFY9hzjYgDNeqBwAA",
};

export function getThemePreviewBlur(themeId: string): string | undefined {
  return THEME_BLUR_DATA[`${themeId}-preview`];
}
