/**
 * Commerce + marketing + advanced blocks for the second editor upgrade batch.
 */
import type { BlockDefinition } from "../types";
import {
  BASIC_BACKGROUND_STYLE,
  BASIC_SPACING_STYLES,
  BASIC_TYPOGRAPHY_STYLES,
  STANDARD_ADVANCED_FIELDS,
  TITLE_CONTENT_FIELD,
} from "./shared-schemas";

export const productCardBlock: Omit<BlockDefinition, "component"> = {
  id: "product-card",
  category: "commerce",
  name: "Product card",
  description: "Single product spotlight",
  icon: "package",
  legacySectionType: "product-card",
  implemented: true,
  thumbnail: { type: "gradient", value: "from-stone-100 to-stone-200" },
  defaultContent: {
    title: "Featured product",
    productSource: "latest",
    productIds: [],
    ctaText: "View product",
  },
  defaultStyles: {
    desktop: { padding: "3rem 1.5rem" },
  },
  settingsSchema: {
    focuses: ["text", "section", "image", "button"],
    content: [
      TITLE_CONTENT_FIELD,
      {
        key: "productSource",
        type: "select",
        label: "Product",
        group: "products",
        focus: "section",
        options: [
          { value: "latest", label: "Latest product" },
          { value: "manual", label: "Pick a product" },
        ],
      },
      {
        key: "productIds",
        type: "productPicker",
        label: "Choose product",
        group: "products",
        focus: "section",
        description: "Select one product (first selected is used).",
        showWhen: { key: "productSource", equals: "manual" },
      },
      {
        key: "ctaText",
        type: "text",
        label: "Button text",
        group: "buttons",
        focus: "button",
        placeholder: "View product",
      },
    ],
    styles: [...BASIC_TYPOGRAPHY_STYLES, BASIC_BACKGROUND_STYLE],
    layout: BASIC_SPACING_STYLES,
    advanced: STANDARD_ADVANCED_FIELDS,
  },
};

export const countdownBlock: Omit<BlockDefinition, "component"> = {
  id: "countdown",
  category: "advanced",
  name: "Countdown",
  description: "Timer for launches and promotions",
  icon: "sparkles",
  legacySectionType: "countdown",
  implemented: true,
  thumbnail: { type: "gradient", value: "from-orange-50 to-amber-100" },
  defaultContent: {
    title: "Sale ends soon",
    subtitle: "Don’t miss these deals",
    endAt: "",
    ctaText: "Shop the sale",
    ctaLink: "/products",
  },
  defaultStyles: {
    desktop: { padding: "4rem 1.5rem", alignment: "center" },
  },
  settingsSchema: {
    focuses: ["text", "section", "button", "link"],
    content: [
      TITLE_CONTENT_FIELD,
      {
        key: "subtitle",
        type: "text",
        label: "Subtitle",
        group: "text",
        focus: ["text", "section"],
      },
      {
        key: "endAt",
        type: "datetime",
        label: "End date & time",
        group: "text",
        focus: "section",
        description: "When the countdown reaches zero",
      },
      {
        key: "ctaText",
        type: "text",
        label: "Button text",
        group: "buttons",
        focus: "button",
      },
      {
        key: "ctaLink",
        type: "link",
        label: "Button link",
        group: "links",
        focus: "link",
      },
    ],
    styles: [...BASIC_TYPOGRAPHY_STYLES, BASIC_BACKGROUND_STYLE],
    layout: BASIC_SPACING_STYLES,
    advanced: STANDARD_ADVANCED_FIELDS,
  },
};

export const ctaBannerBlock: Omit<BlockDefinition, "component"> = {
  id: "cta",
  category: "marketing",
  name: "CTA",
  description: "Call-to-action banner",
  icon: "megaphone",
  legacySectionType: "cta",
  implemented: true,
  pageTemplates: ["home", "product"],
  thumbnail: { type: "gradient", value: "from-rose-50 to-pink-100" },
  defaultContent: {
    title: "Ready to shop?",
    subtitle: "Browse the latest arrivals and exclusive drops.",
    buttonText: "Shop now",
    buttonLink: "/products",
    alignment: "center",
    layout: "banner",
  },
  defaultStyles: {
    desktop: {
      padding: "4rem 1.5rem",
      backgroundColor: "#0a0a0a",
      textColor: "#ffffff",
      alignment: "center",
    },
  },
  settingsSchema: {
    focuses: ["text", "button", "link", "section"],
    content: [
      TITLE_CONTENT_FIELD,
      {
        key: "subtitle",
        type: "textarea",
        label: "Subtitle",
        group: "text",
        focus: ["text", "section"],
      },
      {
        key: "layout",
        type: "select",
        label: "Design layout",
        group: "layout",
        focus: "section",
        options: [
          { value: "banner", label: "Centered banner" },
          { value: "split", label: "Split (text + button)" },
          { value: "card", label: "Contained card" },
          { value: "strip", label: "Compact strip" },
          { value: "stacked", label: "Large stacked" },
        ],
      },
      {
        key: "alignment",
        type: "select",
        label: "Text alignment",
        group: "layout",
        focus: "section",
        options: [
          { value: "left", label: "Left" },
          { value: "center", label: "Center" },
          { value: "right", label: "Right" },
        ],
        showWhen: { key: "layout", in: ["banner", "strip"] },
      },
      {
        key: "buttonText",
        type: "text",
        label: "Button text",
        group: "buttons",
        focus: "button",
      },
      {
        key: "buttonLink",
        type: "link",
        label: "Button link",
        group: "links",
        focus: "link",
      },
      {
        key: "secondaryButtonText",
        type: "text",
        label: "Secondary button",
        group: "buttons",
        focus: "button",
        placeholder: "Optional",
      },
      {
        key: "secondaryButtonLink",
        type: "link",
        label: "Secondary button link",
        group: "links",
        focus: "link",
        showWhen: { key: "secondaryButtonText", notEquals: "" },
      },
    ],
    styles: [...BASIC_TYPOGRAPHY_STYLES, BASIC_BACKGROUND_STYLE],
    layout: BASIC_SPACING_STYLES,
    advanced: STANDARD_ADVANCED_FIELDS,
  },
};

export const featuresGridBlock: Omit<BlockDefinition, "component"> = {
  id: "features",
  category: "marketing",
  name: "Features",
  description: "Highlight key product benefits",
  icon: "sparkles",
  legacySectionType: "features",
  implemented: true,
  pageTemplates: ["home", "product"],
  thumbnail: { type: "gradient", value: "from-violet-50 to-purple-100" },
  defaultContent: {
    title: "Why shop with us",
    subtitle: "Built for a smoother shopping experience",
    layout: "cards",
    cardStyle: "bordered",
    columns: 3,
    alignment: "center",
    showIcons: true,
    items: [
      { title: "Fast shipping", body: "Delivered across Morocco in 2–5 days.", icon: "🚚" },
      { title: "Secure checkout", body: "COD and card payments you can trust.", icon: "🔒" },
      { title: "Easy returns", body: "14-day returns on unused items.", icon: "↩️" },
    ],
  },
  defaultStyles: {
    desktop: { padding: "3.5rem 1.5rem" },
  },
  settingsSchema: {
    focuses: ["text", "section"],
    content: [
      TITLE_CONTENT_FIELD,
      {
        key: "subtitle",
        type: "textarea",
        label: "Subtitle",
        group: "text",
        focus: ["text", "section"],
        placeholder: "Short supporting line…",
      },
      {
        key: "layout",
        type: "select",
        label: "Design layout",
        group: "layout",
        focus: "section",
        options: [
          { value: "cards", label: "Cards" },
          { value: "minimal", label: "Minimal grid" },
          { value: "icon-left", label: "Icon + text rows" },
          { value: "numbered", label: "Numbered steps" },
          { value: "centered", label: "Centered icons" },
          { value: "strip", label: "Trust strip" },
        ],
      },
      {
        key: "cardStyle",
        type: "select",
        label: "Card style",
        group: "style",
        focus: "section",
        options: [
          { value: "bordered", label: "Bordered" },
          { value: "soft", label: "Soft fill" },
          { value: "plain", label: "Plain" },
          { value: "accent", label: "Accent wash" },
        ],
        showWhen: { key: "layout", in: ["cards", "minimal", "centered", "numbered"] },
      },
      {
        key: "columns",
        type: "select",
        label: "Columns",
        group: "layout",
        focus: "section",
        options: [
          { value: "2", label: "2" },
          { value: "3", label: "3" },
          { value: "4", label: "4" },
        ],
        showWhen: { key: "layout", in: ["cards", "minimal", "centered", "numbered"] },
      },
      {
        key: "alignment",
        type: "select",
        label: "Text alignment",
        group: "layout",
        focus: "section",
        options: [
          { value: "left", label: "Left" },
          { value: "center", label: "Center" },
        ],
        showWhen: { key: "layout", in: ["cards", "minimal", "centered", "numbered"] },
      },
      {
        key: "showIcons",
        type: "toggle",
        label: "Show icons",
        group: "style",
        focus: "section",
      },
      {
        key: "items",
        type: "itemList",
        label: "Features",
        itemLabel: "Feature",
        maxItems: 8,
        group: "text",
        focus: ["text", "section"],
        itemFields: [
          { key: "icon", type: "text", label: "Icon / emoji", placeholder: "✨" },
          { key: "title", type: "text", label: "Title", placeholder: "Feature name" },
          { key: "body", type: "textarea", label: "Description", placeholder: "Short benefit…" },
        ],
      },
    ],
    styles: [...BASIC_TYPOGRAPHY_STYLES, BASIC_BACKGROUND_STYLE],
    layout: BASIC_SPACING_STYLES,
    advanced: STANDARD_ADVANCED_FIELDS,
  },
};

export const searchBarBlock: Omit<BlockDefinition, "component"> = {
  id: "search",
  category: "forms",
  name: "Search",
  description: "Product search bar",
  icon: "search",
  legacySectionType: "search",
  implemented: true,
  thumbnail: { type: "gradient", value: "from-teal-50 to-cyan-100" },
  defaultContent: {
    title: "Find a product",
    placeholder: "Search the catalog…",
    buttonText: "Search",
  },
  defaultStyles: {
    desktop: { padding: "2.5rem 1.5rem" },
  },
  settingsSchema: {
    focuses: ["text", "section"],
    content: [
      TITLE_CONTENT_FIELD,
      {
        key: "placeholder",
        type: "text",
        label: "Placeholder",
        group: "text",
        focus: ["text", "section"],
      },
      {
        key: "buttonText",
        type: "text",
        label: "Button text",
        group: "buttons",
        focus: "button",
      },
    ],
    styles: [...BASIC_TYPOGRAPHY_STYLES, BASIC_BACKGROUND_STYLE],
    layout: BASIC_SPACING_STYLES,
    advanced: STANDARD_ADVANCED_FIELDS,
  },
};

export const embedBlock: Omit<BlockDefinition, "component"> = {
  id: "embed",
  category: "advanced",
  name: "Embed",
  description: "Maps, Instagram, or trusted widgets",
  icon: "box",
  legacySectionType: "embed",
  implemented: true,
  thumbnail: { type: "gradient", value: "from-purple-50 to-fuchsia-100" },
  defaultContent: {
    title: "",
    url: "",
    aspectRatio: "16 / 9",
  },
  defaultStyles: {
    desktop: { padding: "2rem 1.5rem" },
  },
  settingsSchema: {
    focuses: ["section", "text"],
    content: [
      TITLE_CONTENT_FIELD,
      {
        key: "url",
        type: "url",
        label: "Embed URL",
        group: "text",
        focus: "section",
        placeholder: "https://www.google.com/maps/embed?…",
        description: "Allowed: Google Maps, YouTube, Vimeo, Instagram (embed URLs)",
      },
      {
        key: "aspectRatio",
        type: "select",
        label: "Aspect ratio",
        group: "layout",
        focus: "section",
        options: [
          { value: "16 / 9", label: "16:9" },
          { value: "4 / 3", label: "4:3" },
          { value: "1 / 1", label: "1:1" },
          { value: "21 / 9", label: "21:9" },
        ],
      },
    ],
    styles: [BASIC_BACKGROUND_STYLE],
    layout: BASIC_SPACING_STYLES,
    advanced: STANDARD_ADVANCED_FIELDS,
  },
};
