import type { BlockDefinition } from "../types";
import {
  BASIC_BACKGROUND_STYLE,
  BASIC_SPACING_STYLES,
  BASIC_TYPOGRAPHY_STYLES,
  STANDARD_ADVANCED_FIELDS,
  TITLE_CONTENT_FIELD,
} from "./shared-schemas";

export const featuredCollectionsBlock: Omit<BlockDefinition, "component"> = {
  id: "collection-banner",
  category: "commerce",
  name: "Collection banner",
  description: "Showcase featured collections in multiple layouts",
  icon: "grid",
  legacySectionType: "featured-collections",
  implemented: true,
  thumbnail: { type: "gradient", value: "from-indigo-50 to-blue-100" },
  defaultContent: {
    title: "Featured Collections",
    subtitle: "Explore the shop by category",
    collectionSource: "featured",
    limit: 6,
    layout: "grid",
    cardStyle: "overlay",
    columns: 3,
    showViewAll: true,
    showDescription: true,
  },
  defaultStyles: {
    desktop: {
      padding: "2rem 1.5rem",
    },
  },
  settingsSchema: {
    focuses: ["text", "section", "image"],
    content: [
      TITLE_CONTENT_FIELD,
      {
        key: "subtitle",
        type: "textarea",
        label: "Subtitle",
        group: "text",
        focus: ["text", "section"],
        placeholder: "Short supporting line…",
      },
      {
        key: "layout",
        type: "select",
        label: "Design layout",
        group: "layout",
        focus: "section",
        options: [
          { value: "grid", label: "Grid" },
          { value: "carousel", label: "Carousel" },
          { value: "editorial", label: "Editorial" },
          { value: "mosaic", label: "Mosaic" },
          { value: "overlay", label: "Tall overlay" },
          { value: "list", label: "List" },
        ],
      },
      {
        key: "cardStyle",
        type: "select",
        label: "Card style",
        group: "style",
        focus: "section",
        options: [
          { value: "overlay", label: "Text on image" },
          { value: "below", label: "Text below" },
          { value: "bordered", label: "Bordered card" },
        ],
        showWhen: { key: "layout", in: ["grid", "carousel", "editorial", "mosaic"] },
      },
      {
        key: "columns",
        type: "select",
        label: "Columns",
        group: "layout",
        focus: "section",
        options: [
          { value: "2", label: "2" },
          { value: "3", label: "3" },
          { value: "4", label: "4" },
        ],
        showWhen: { key: "layout", in: ["grid", "overlay"] },
      },
      {
        key: "collectionSource",
        type: "select",
        label: "Collections to show",
        group: "products",
        focus: "section",
        options: [
          { value: "featured", label: "Featured only" },
          { value: "all", label: "All collections" },
          { value: "manual", label: "Pick collections" },
        ],
      },
      {
        key: "collectionIds",
        type: "collectionPicker",
        label: "Choose collections",
        group: "products",
        focus: "section",
        description: "Select which collections appear in this section.",
        showWhen: { key: "collectionSource", equals: "manual" },
      },
      {
        key: "limit",
        type: "number",
        label: "Max collections",
        group: "products",
        focus: "section",
        placeholder: "6",
      },
      {
        key: "showViewAll",
        type: "toggle",
        label: "Show “View all” link",
        group: "buttons",
        focus: "section",
      },
      {
        key: "showDescription",
        type: "toggle",
        label: "Show descriptions",
        group: "text",
        focus: ["text", "section"],
      },
    ],
    styles: [
      BASIC_BACKGROUND_STYLE,
      ...BASIC_TYPOGRAPHY_STYLES.filter((f) => f.key !== "fontSize"),
    ],
    layout: BASIC_SPACING_STYLES,
    advanced: STANDARD_ADVANCED_FIELDS,
  },
};
