import type { BlockDefinition } from "../types";
import {
  BUTTON_VARIANT_OPTIONS,
  HERO_LAYOUT_GROUPS,
  HERO_STYLE_GROUPS,
  STANDARD_ADVANCED_FIELDS,
} from "./shared-schemas";

export const heroBlock: Omit<BlockDefinition, "component"> = {
  id: "hero",
  category: "marketing",
  name: "Hero",
  description: "Large banner with headline and CTA",
  icon: "image",
  legacySectionType: "hero",
  implemented: true,
  thumbnail: { type: "gradient", value: "from-blue-50 to-indigo-100" },
  defaultContent: {
    headline: "New season",
    subheadline: "Fewer pieces. Better materials. Built to last.",
    ctaText: "Shop now",
    ctaLink: "/products",
    showStoreDescription: false,
    showBrand: true,
    overlay: true,
    alignment: "center",
    minHeight: "100svh",
    padding: "0",
    backgroundColor: "#0a0a0a",
    textColor: "#ffffff",
  },
  defaultStyles: {
    desktop: {
      padding: "0",
      alignment: "center",
      minHeight: "100svh",
    },
  },
  settingsSchema: {
    focuses: ["text", "image", "button", "link"],
    content: [
      {
        key: "eyebrow",
        type: "text",
        label: "Eyebrow",
        group: "text",
        focus: ["text", "section"],
        placeholder: "New season · Limited",
      },
      {
        key: "headline",
        type: "text",
        label: "Headline",
        group: "text",
        focus: ["text", "section"],
        placeholder: "Uses store name if empty",
      },
      {
        key: "accentHeadline",
        type: "text",
        label: "Accent line",
        group: "text",
        focus: ["text", "section"],
        placeholder: "Up to 25% off",
        description: "Secondary highlight under or beside the headline",
      },
      {
        key: "subheadline",
        type: "textarea",
        label: "Subtitle",
        group: "text",
        focus: ["text", "section"],
        placeholder: "Uses store description if empty",
      },
      {
        key: "showStoreDescription",
        type: "toggle",
        label: "Use store description as subtitle",
        group: "text",
        focus: ["text", "section"],
        description: "When subtitle is empty, show the store description",
      },
      {
        key: "showBrand",
        type: "toggle",
        label: "Show store name as brand",
        group: "text",
        focus: ["text", "section"],
        description: "Hero-level brand signal above the headline (recommended for overlay heroes)",
        showWhen: { key: "overlay", equals: true },
      },
      {
        key: "imageUrl",
        type: "image",
        label: "Hero image",
        group: "images",
        focus: ["image", "section"],
        altKey: "imageAlt",
      },
      {
        key: "ctaText",
        type: "text",
        label: "Primary button",
        group: "buttons",
        focus: "button",
        placeholder: "Shop now",
      },
      {
        key: "ctaLink",
        type: "link",
        label: "Primary button link",
        group: "links",
        focus: "link",
        placeholder: "/products or https://...",
      },
      {
        key: "secondaryCtaText",
        type: "text",
        label: "Secondary button",
        group: "buttons",
        focus: "button",
        placeholder: "Learn more",
      },
      {
        key: "secondaryCtaLink",
        type: "link",
        label: "Secondary button link",
        group: "links",
        focus: "link",
        placeholder: "/about",
      },
      {
        key: "overlay",
        type: "toggle",
        label: "Text over image",
        group: "images",
        focus: ["image", "section"],
        description: "Full-bleed image with headline overlay",
      },
      {
        key: "layout",
        type: "variant",
        label: "Hero layout",
        group: "layout",
        focus: "section",
        options: [
          { value: "stack", label: "Stack" },
          { value: "split", label: "Split" },
          { value: "editorial", label: "Editorial" },
        ],
      },
    ],
    styles: [
      ...HERO_STYLE_GROUPS,
      {
        key: "ctaVariant",
        type: "variant",
        label: "Button style",
        group: "buttons",
        focus: "button",
        options: BUTTON_VARIANT_OPTIONS,
      },
    ],
    layout: HERO_LAYOUT_GROUPS,
    advanced: STANDARD_ADVANCED_FIELDS,
  },
};
