import type { BlockDefinition } from "../types";
import {
  BASIC_BACKGROUND_STYLE,
  BASIC_TYPOGRAPHY_STYLES,
  BUTTON_VARIANT_OPTIONS,
  PRODUCT_GRID_LAYOUT_FIELDS,
  STANDARD_ADVANCED_FIELDS,
  TITLE_CONTENT_FIELD,
} from "./shared-schemas";

const PRODUCT_SOURCE_FIELDS: BlockDefinition["settingsSchema"]["content"] = [
  TITLE_CONTENT_FIELD,
  {
    key: "subtitle",
    type: "text",
    label: "Subtitle",
    group: "text",
    focus: ["text", "section"],
    placeholder: "Optional supporting line",
  },
  {
    key: "layout",
    type: "select",
    label: "Layout style",
    group: "products",
    focus: "section",
    description: "Or use Browse designs for a full preset",
    options: [
      { value: "grid", label: "Grid" },
      { value: "carousel", label: "Carousel" },
      { value: "list", label: "List rows" },
      { value: "spotlight", label: "Spotlight" },
      { value: "dense", label: "Dense showcase" },
    ],
  },
  {
    key: "cardStyle",
    type: "select",
    label: "Card style",
    group: "products",
    focus: "section",
    options: [
      { value: "minimal", label: "Minimal" },
      { value: "bordered", label: "Bordered" },
      { value: "overlay", label: "Overlay" },
    ],
  },
  {
    key: "productSource",
    type: "select",
    label: "Products to show",
    group: "products",
    focus: "section",
    options: [
      { value: "latest", label: "Latest products" },
      { value: "manual", label: "Pick existing products" },
    ],
  },
  {
    key: "productIds",
    type: "productPicker",
    label: "Choose products",
    group: "products",
    focus: "section",
    description: "Select products from your catalog. Sample preview items never publish.",
    showWhen: { key: "productSource", equals: "manual" },
  },
  {
    key: "limit",
    type: "number",
    label: "Max products",
    group: "products",
    focus: "section",
    placeholder: "8",
  },
  {
    key: "offset",
    type: "number",
    label: "Skip first",
    group: "products",
    focus: "section",
    placeholder: "0",
    description: "Skip N newest products (useful for a second grid)",
    showWhen: { key: "productSource", equals: "latest" },
  },
  {
    key: "showViewAll",
    type: "toggle",
    label: "Show “View all”",
    group: "products",
    focus: "section",
  },
  {
    key: "viewAllStyle",
    type: "select",
    label: "View all button style",
    group: "buttons",
    focus: ["button", "section"],
    options: [
      { value: "link", label: "Text link" },
      { value: "", label: "Primary" },
      { value: "secondary", label: "Secondary" },
      { value: "outline", label: "Outline" },
      { value: "ghost", label: "Ghost" },
    ],
    showWhen: { key: "showViewAll", equals: true },
  },
  {
    key: "showCardButton",
    type: "toggle",
    label: "Show button on product cards",
    group: "buttons",
    focus: ["button", "section"],
  },
  {
    key: "cardButtonText",
    type: "text",
    label: "Card button text",
    group: "buttons",
    focus: ["button", "section"],
    placeholder: "Shop",
    showWhen: { key: "showCardButton", equals: true },
  },
  {
    key: "cardButtonStyle",
    type: "select",
    label: "Card button style",
    group: "buttons",
    focus: ["button", "section"],
    options: BUTTON_VARIANT_OPTIONS,
    showWhen: { key: "showCardButton", equals: true },
  },
];

export const productGridBlock: Omit<BlockDefinition, "component"> = {
  id: "product-grid",
  category: "commerce",
  name: "Product grid",
  description: "Grid, carousel, or list of products from your catalog",
  icon: "shopping-bag",
  legacySectionType: "product-grid",
  implemented: true,
  thumbnail: { type: "gradient", value: "from-blue-50 to-slate-100" },
  defaultContent: {
    title: "Products",
    subtitle: "",
    productSource: "latest",
    limit: 8,
    offset: 0,
    showViewAll: true,
    layout: "grid",
    cardStyle: "minimal",
    showCardButton: false,
    cardButtonText: "Shop",
    cardButtonStyle: "",
    viewAllStyle: "link",
  },
  defaultStyles: {
    desktop: {
      padding: "2rem 1.5rem",
    },
  },
  settingsSchema: {
    focuses: ["text", "button", "section"],
    content: PRODUCT_SOURCE_FIELDS,
    styles: [
      BASIC_BACKGROUND_STYLE,
      ...BASIC_TYPOGRAPHY_STYLES.filter((f) => f.key !== "fontSize"),
    ],
    layout: PRODUCT_GRID_LAYOUT_FIELDS,
    advanced: STANDARD_ADVANCED_FIELDS,
  },
};

export const featuredProductsBlock: Omit<BlockDefinition, "component"> = {
  id: "featured-products",
  category: "commerce",
  name: "Featured products",
  description: "Hand-picked product highlights — pick designs & products",
  icon: "star",
  legacySectionType: "product-grid",
  implemented: true,
  thumbnail: { type: "gradient", value: "from-yellow-50 to-amber-100" },
  defaultContent: {
    title: "Featured products",
    subtitle: "",
    productSource: "manual",
    limit: 4,
    showViewAll: false,
    layout: "grid",
    cardStyle: "bordered",
    showCardButton: true,
    cardButtonText: "View product",
    cardButtonStyle: "",
    viewAllStyle: "link",
  },
  defaultStyles: {
    desktop: {
      padding: "2rem 1.5rem",
    },
  },
  settingsSchema: {
    focuses: ["text", "button", "section"],
    content: PRODUCT_SOURCE_FIELDS.map((field) =>
      field.key === "limit" ? { ...field, placeholder: "4" } : field
    ),
    styles: [BASIC_BACKGROUND_STYLE],
    layout: PRODUCT_GRID_LAYOUT_FIELDS,
    advanced: STANDARD_ADVANCED_FIELDS,
  },
};
