import {
  Rocket,
  Layout,
  Truck,
  Globe,
  CreditCard,
  Megaphone,
  UserCircle,
  ArrowLeftRight,
  Package,
  BarChart3,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export type HelpCategory = {
  id: string;
  title: string;
  description: string;
  icon: LucideIcon;
};

export type HelpArticle = {
  slug: string;
  title: string;
  excerpt: string;
  categoryId: string;
  body: string[];
  popular?: boolean;
  keywords?: string[];
};

export const HELP_CATEGORIES: HelpCategory[] = [
  {
    id: "getting-started",
    title: "Getting started",
    description: "Launch your store and publish your first products.",
    icon: Rocket,
  },
  {
    id: "catalog",
    title: "Catalog",
    description: "Products, collections, categories, and inventory.",
    icon: Package,
  },
  {
    id: "store-builder",
    title: "Store builder",
    description: "Design pages, sections, and your brand look.",
    icon: Layout,
  },
  {
    id: "orders-cod",
    title: "Orders & payments",
    description: "COD, Stripe, PayPal, checkout, and fulfillment.",
    icon: Truck,
  },
  {
    id: "domains-hosting",
    title: "Domains & hosting",
    description: "Custom domains, SSL, and performance.",
    icon: Globe,
  },
  {
    id: "billing",
    title: "Billing & plans",
    description: "Subscriptions, trials, and invoices.",
    icon: CreditCard,
  },
  {
    id: "marketing",
    title: "Marketing",
    description:
      "Email, ads pixels, and discounts.",
    icon: Megaphone,
  },
  {
    id: "analytics",
    title: "Analytics",
    description: "Traffic, conversion, and reports.",
    icon: BarChart3,
  },
  {
    id: "account",
    title: "Account",
    description: "Login, team access, and security.",
    icon: UserCircle,
  },
  {
    id: "migration",
    title: "Migration",
    description: "Move from Shopify, WooCommerce, and more.",
    icon: ArrowLeftRight,
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    description: "Fix common issues quickly.",
    icon: Wrench,
  },
];

export const HELP_ARTICLES: HelpArticle[] = [
  // Getting started
  {
    slug: "how-long-does-setup-take",
    title: "How long does setup take?",
    excerpt: "Most merchants launch in under five minutes with the visual builder.",
    categoryId: "getting-started",
    popular: true,
    keywords: ["setup", "launch", "start", "onboarding"],
    body: [
      "Ettajer is built for speed. After you sign up, pick a template and start editing visually — no code required.",
      "Most merchants publish their first storefront in under five minutes. Product import, COD checkout, and domain connection can be added right after launch.",
      "If you need a hand, our support team can walk you through your first publish.",
    ],
  },
  {
    slug: "create-your-first-product",
    title: "Create your first product",
    excerpt: "Add photos, pricing, variants, and inventory — or import from a dropshipping supplier.",
    categoryId: "getting-started",
    popular: true,
    keywords: ["product", "add", "catalog", "photo", "dropshipping", "import"],
    body: [
      "Open Dashboard → Products, then click Add product. Choose a product type: physical, digital, service, or dropshipping.",
      "For dropshipping, pick AliExpress, CJ, or BigBuy, paste a supplier link, and Import — photos, price, variants, and specs fill in automatically. You can clear the link and import another anytime.",
      "Upload images, set your selling price and compare-at price, then add inventory or mark stock as coming from the supplier.",
      "Use variants (size, color) with optional option images, highlights for the product page, and SEO URL handle before you publish.",
      "Save as draft to keep working, or Publish when you are ready. Draft products stay hidden on your storefront until published.",
    ],
  },
  {
    slug: "publish-your-storefront",
    title: "Publish your storefront",
    excerpt: "Make your store live and share your store URL with customers.",
    categoryId: "getting-started",
    keywords: ["publish", "live", "launch", "url"],
    body: [
      "Open Themes in your dashboard, customize your homepage in the visual editor, then click Publish.",
      "Your store gets a default Ettajer URL immediately. You can connect a custom domain anytime from Settings.",
      "After publishing, test checkout on your phone — most Moroccan buyers shop on mobile.",
    ],
  },
  // Catalog
  {
    slug: "collections-vs-categories",
    title: "Collections vs categories",
    excerpt: "When to use each and how they appear on your storefront.",
    categoryId: "catalog",
    popular: true,
    keywords: ["collection", "category", "organize"],
    body: [
      "Categories classify products by type (e.g. Shoes, Accessories). Collections are curated groups you build for campaigns (e.g. Summer Sale, Best Sellers).",
      "Manage categories from Dashboard → Categories and collections from Dashboard → Collections.",
      "Both appear in navigation and product grids. Use collections for merchandising and categories for browse structure.",
    ],
  },
  {
    slug: "manage-product-inventory",
    title: "Manage product inventory",
    excerpt: "Track stock levels and avoid overselling.",
    categoryId: "catalog",
    keywords: ["inventory", "stock", "quantity"],
    body: [
      "Open Dashboard → Products → Inventory to see stock across all variants.",
      "Set quantity per variant when editing a product. When stock hits zero, buyers see out-of-stock on the storefront.",
      "Update inventory after receiving new shipments or processing returns.",
    ],
  },
  {
    slug: "import-products-csv",
    title: "Import products via CSV",
    excerpt: "Bulk upload your catalog from a spreadsheet.",
    categoryId: "catalog",
    keywords: ["import", "csv", "bulk", "upload"],
    body: [
      "Export or build a CSV with columns for title, price, description, images, and variants.",
      "Go to Dashboard → Products → Import, upload your file, and map columns to Ettajer fields.",
      "Review the preview before confirming. Large imports may take a few minutes.",
    ],
  },
  {
    slug: "product-images-best-practices",
    title: "Product images best practices",
    excerpt: "Photos that convert on mobile in Morocco.",
    categoryId: "catalog",
    keywords: ["images", "photos", "product"],
    body: [
      "Use square or 4:5 images at least 1200px wide. Bright, natural lighting works best for lifestyle products.",
      "Show the product alone and in context. First image is the thumbnail everywhere — make it clear and uncluttered.",
      "Ettajer optimizes images automatically for fast loading on mobile networks.",
    ],
  },
  {
    slug: "sell-digital-products",
    title: "Sell digital products and ebooks",
    excerpt: "Deliver files after purchase without shipping.",
    categoryId: "catalog",
    popular: true,
    keywords: ["digital", "ebook", "pdf", "download", "course"],
    body: [
      "When creating a product, set type to Digital. Upload a front (and optional back) cover, then upload the PDF under Ebook file.",
      "PDFs can be up to 50 MB. Keep covers as JPG/PNG/WebP under 10 MB for fast mobile loading.",
      "Digital products skip shipping — checkout still supports COD or card depending on your payment settings.",
      "After payment or confirmation, customers receive download access according to your fulfillment flow.",
      "Do not upload copyrighted files you do not own. Add your copyright notice on the product when needed.",
    ],
  },
  {
    slug: "dropshipping-with-ettajer",
    title: "Start dropshipping with Ettajer",
    excerpt: "Import from AliExpress, CJ, or BigBuy and sell without stock.",
    categoryId: "catalog",
    popular: true,
    keywords: ["dropshipping", "aliexpress", "cj", "bigbuy", "supplier"],
    body: [
      "Create a product and choose Dropshipping. Pick AliExpress, CJ Dropshipping, or BigBuy.",
      "Paste the supplier product URL and click Import — title, images, price, and variants fill in for you to edit.",
      "Adjust your selling price for margin after shipping and COD fees. Hide supplier branding in titles and images when possible.",
      "When an order arrives, fulfill with your supplier using the customer address from Dashboard → Orders.",
      "Keep inventory honest: if the supplier is out of stock, mark the product unavailable so you do not take unpaid courier trips.",
    ],
  },
  {
    slug: "product-variants-size-color",
    title: "Set up size and color variants",
    excerpt: "Let buyers pick options without duplicate product pages.",
    categoryId: "catalog",
    keywords: ["variants", "size", "color", "options"],
    body: [
      "Edit a product and add options such as Size or Color. Each combination becomes a variant with its own SKU and stock.",
      "Optional: attach an image per option so the gallery updates when the buyer selects a color.",
      "Set price overrides per variant only when needed (e.g. XL costs more).",
      "On the storefront, buyers choose options before Add to cart — out-of-stock combinations are blocked automatically.",
      "Keep option names short and consistent across the catalog so filters and reports stay readable.",
    ],
  },
  // Store builder
  {
    slug: "use-the-visual-builder",
    title: "Use the visual builder",
    excerpt: "Drag sections, edit text inline, and preview changes live.",
    categoryId: "store-builder",
    popular: true,
    keywords: ["builder", "editor", "theme", "design"],
    body: [
      "Open Themes → Customize to enter the visual builder. Click any section to edit content, images, or layout.",
      "Add new blocks from the left panel — hero banners, product grids, testimonials, and more.",
      "Changes save as drafts until you publish. Preview on desktop and mobile before going live.",
    ],
  },
  {
    slug: "add-and-arrange-sections",
    title: "Add and arrange sections",
    excerpt: "Build your homepage with drag-and-drop blocks.",
    categoryId: "store-builder",
    keywords: ["sections", "blocks", "layout"],
    body: [
      "In the theme editor, open the Add panel on the left. Pick a block type and drop it where you want it on the page.",
      "Drag sections to reorder. Click a section to edit its content in the right panel.",
      "Delete sections you do not need — less clutter improves conversion on mobile.",
    ],
  },
  {
    slug: "customize-brand-colors-and-fonts",
    title: "Customize brand colors and fonts",
    excerpt: "Match your logo and keep your storefront consistent.",
    categoryId: "store-builder",
    keywords: ["colors", "fonts", "brand", "style"],
    body: [
      "In the theme editor, open Global styles to set primary colors, backgrounds, and typography.",
      "Colors apply across buttons, headings, and accents automatically.",
      "For best results, use two brand colors and one neutral — minimal palettes convert better on mobile.",
    ],
  },
  {
    slug: "preview-mobile-storefront",
    title: "Preview your store on mobile",
    excerpt: "Most buyers in Morocco shop on phones — always check mobile view.",
    categoryId: "store-builder",
    keywords: ["mobile", "preview", "responsive"],
    body: [
      "In the theme editor, switch to mobile preview using the device toggle at the top.",
      "Check that text is readable, buttons are tappable, and product images load quickly.",
      "Publish only after mobile looks right — it drives the majority of COD orders.",
    ],
  },
  {
    slug: "save-draft-vs-publish",
    title: "Save draft vs publish",
    excerpt: "Understand when changes go live on your storefront.",
    categoryId: "store-builder",
    keywords: ["draft", "publish", "save"],
    body: [
      "Edits in the builder are saved as drafts automatically. Your live storefront does not change until you click Publish.",
      "Use Save draft when experimenting. Publish when you are ready for customers to see updates.",
      "You can revert by republishing a previous version from Themes if needed.",
    ],
  },
  // Orders & payments
  {
    slug: "how-cod-checkout-works",
    title: "How COD checkout works",
    excerpt: "Cash on delivery is built in — keep it on while you add cards or PayPal.",
    categoryId: "orders-cod",
    popular: true,
    keywords: ["cod", "cash", "delivery", "checkout", "payments"],
    body: [
      "Ettajer includes native Cash on Delivery — it is on by default for new stores. Buyers enter name, phone, city, and address — no card required.",
      "Customize the COD message, minimum order, and checkout note under Settings → Checkout. Review all payment options anytime in Settings → Payments.",
      "You can also accept PayPal now (money goes to your PayPal account). Stripe card payments (Apple Pay & Google Pay) appear in Settings → Payments but cannot be activated yet — expected around October 2026. Ettajer never holds customer funds. See Set up online payments.",
      "COD orders appear in Dashboard → Orders as unpaid until delivery. PayPal orders are marked paid after the customer completes checkout.",
    ],
  },
  {
    slug: "set-up-online-payments",
    title: "Set up online payments (PayPal now · Stripe soon)",
    excerpt: "Connect PayPal today. Stripe cards turn on in about 2 months.",
    categoryId: "orders-cod",
    popular: true,
    keywords: [
      "stripe",
      "paypal",
      "payments",
      "card",
      "checkout",
      "connect",
      "online",
    ],
    body: [
      "Open Dashboard → Settings → Payments. Keep COD on if you still deliver cash orders — you can run COD and PayPal together.",
      "Stripe (cards, Apple Pay, Google Pay): listed in Payments with an “In ~2 months” badge. The toggle is disabled until we turn Stripe on around October 2026. You cannot activate it yet.",
      "PayPal: turn PayPal on → create an app at developer.paypal.com → paste Client ID and Secret Key 1 → choose Sandbox (test) or Live → click Verify & connect. Shoppers pay with PayPal buttons; funds go to your PayPal account.",
      "PayPal does not support MAD, DZD, or TND. If your store currency is MAD, switch to USD or EUR in Settings → Languages before connecting PayPal.",
      "After connecting PayPal, place a small test order (Sandbox first). Confirm the order shows as Paid in Dashboard → Orders and that money appears in PayPal.",
      "Detailed guides: Connect PayPal at checkout, and Connect Stripe for card payments (coming soon).",
    ],
  },
  {
    slug: "connect-stripe-for-cards",
    title: "Stripe for card payments (coming in ~2 months)",
    excerpt: "Stripe is visible in Payments but not activatable yet — around October 2026.",
    categoryId: "orders-cod",
    popular: true,
    keywords: [
      "stripe",
      "connect",
      "card",
      "apple pay",
      "google pay",
      "payout",
      "coming soon",
    ],
    body: [
      "Stripe will let shoppers pay with cards, Apple Pay, and Google Pay. Money will go to your Stripe bank account — Ettajer will not hold funds.",
      "Today: open Settings → Payments. You’ll see Stripe with an “In ~2 months” badge and a disabled toggle. You cannot turn it on or start Connect yet.",
      "We expect to enable Stripe around October 2026. When it’s live, you’ll Connect Stripe, finish onboarding, and Refresh — then cards appear at checkout.",
      "Until then, use Cash on delivery and/or PayPal so customers can still checkout and you still get paid online.",
      "See Set up online payments and Connect PayPal at checkout for what you can enable now.",
    ],
  },
  {
    slug: "connect-paypal-checkout",
    title: "Connect PayPal at checkout",
    excerpt: "Paste Client ID and Secret, verify with PayPal, then get paid.",
    categoryId: "orders-cod",
    popular: true,
    keywords: [
      "paypal",
      "client id",
      "secret",
      "sandbox",
      "live",
      "checkout",
    ],
    body: [
      "Create a PayPal developer account and an app (e.g. “ettajer”) at developer.paypal.com → Apps & Credentials.",
      "Copy the Client ID and Secret Key 1. In Ettajer open Settings → Payments, turn PayPal on, paste both fields, pick Sandbox or Live (must match the credentials), then click Verify & connect.",
      "Verify talks to PayPal with your credentials. Green success means checkout can charge. Toggle stays on and PayPal buttons appear on your storefront checkout.",
      "Currency: PayPal needs a supported currency such as USD or EUR — not MAD. Change currency in Settings → Languages, then verify again.",
      "When a customer pays, Ettajer captures the payment and creates a Paid order. Money settles in the PayPal account tied to your app — you do not need to mark the order paid manually.",
      "Use Sandbox + a PayPal sandbox buyer for tests. Switch Mode to Live and paste Live credentials before accepting real payments.",
    ],
  },
  {
    slug: "confirm-cod-orders-by-phone",
    title: "Confirm COD orders by phone or WhatsApp",
    excerpt: "Call buyers before shipping to cut refused deliveries.",
    categoryId: "orders-cod",
    popular: true,
    keywords: ["confirm", "phone", "whatsapp", "cod", "call"],
    body: [
      "Open the order in Dashboard → Orders. You will see customer name, phone, city, and address.",
      "Call or WhatsApp from the order page within a few hours. Confirm the product, total, and delivery window.",
      "If the number is invalid or the buyer cancels, mark the order cancelled before you hand it to the courier.",
      "Use Confirm order on the order page after you reach the buyer — status becomes Confirmed (safe to pack).",
      "Add a short merchant note on the order (e.g. “Confirmed 18:40”) so your team knows it is safe to ship.",
    ],
  },
  {
    slug: "order-statuses-explained",
    title: "Order statuses explained",
    excerpt: "Pending, confirmed, shipped, delivered, cancelled, and returns.",
    categoryId: "orders-cod",
    keywords: ["status", "fulfillment", "shipped", "delivered", "pending"],
    body: [
      "Pending — new order, not yet confirmed with the customer (COD) or waiting on online payment status.",
      "Confirmed — buyer verified; ready for packing or courier pickup.",
      "Shipped — handed to the delivery company; add tracking in notes if you have it.",
      "Delivered — customer received the parcel (and paid COD if applicable).",
      "Payment status is separate: COD stays unpaid until delivery; Stripe and PayPal orders are paid when checkout completes.",
      "Cancelled / returned — stop fulfillment; restock inventory when items come back.",
      "Update status from the order page so history stays accurate for support and analytics.",
    ],
  },
  {
    slug: "set-up-whatsapp-cod-verification",
    title: "Set up WhatsApp COD verification",
    excerpt: "Confirm orders before you ship to cut fake deliveries.",
    categoryId: "orders-cod",
    popular: true,
    keywords: ["whatsapp", "sms", "verification", "cod"],
    body: [
      "Enable Cash on Delivery in Settings → Payments so shoppers can order without a card.",
      "Add your WhatsApp number in Settings → Storefront contact so customers can reach you from the shop footer.",
      "After an order arrives in Dashboard → Orders, confirm details with the customer on WhatsApp or phone before you pack and hand off to your courier.",
    ],
  },
  {
    slug: "reduce-fake-cod-orders",
    title: "Reduce fake COD orders",
    excerpt: "Confirm buyers before you ship.",
    categoryId: "orders-cod",
    popular: true,
    keywords: ["fake", "fraud", "cod", "verification"],
    body: [
      "Fake COD orders are a common problem in Morocco. Confirm name, phone, and address before you dispatch.",
      "COD is on by default. Review new orders in Dashboard → Orders and reach out on WhatsApp when something looks off.",
      "Merchants typically see fewer returned or refused deliveries after confirming buyers before shipping.",
    ],
  },
  {
    slug: "cod-address-fields-morocco",
    title: "COD address fields for Morocco",
    excerpt: "City, neighborhood, and phone — what to collect at checkout.",
    categoryId: "orders-cod",
    keywords: ["address", "city", "morocco", "neighborhood"],
    body: [
      "COD checkout collects name, phone, city, neighborhood (quartier), and full address — fields Moroccan couriers expect.",
      "Require a valid mobile number. Landlines make delivery harder.",
      "Limit where you deliver in Settings → Shipping by choosing cities for each zone.",
    ],
  },
  {
    slug: "handle-refused-cod-deliveries",
    title: "Handle refused COD deliveries",
    excerpt: "What to do when a customer refuses the package.",
    categoryId: "orders-cod",
    keywords: ["refused", "return", "cod", "delivery"],
    body: [
      "Mark the order as refused or returned in Dashboard → Orders. This keeps your records accurate.",
      "Contact the customer via phone or WhatsApp to understand why — often it is wrong size or changed mind.",
      "Enable pre-shipment verification to catch non-serious buyers before you pay courier fees.",
    ],
  },
  {
    slug: "manage-orders-and-fulfillment",
    title: "Manage orders and fulfillment",
    excerpt: "Update status, notify customers, and track deliveries.",
    categoryId: "orders-cod",
    popular: true,
    keywords: ["orders", "fulfill", "ship", "status"],
    body: [
      "Open any order from Dashboard → Orders to see line items, customer info, payment method (COD, Stripe, or PayPal), and whether it is paid.",
      "Update order status — pending, confirmed, shipped, delivered. Customers can be notified automatically.",
      "Online payments are already paid at checkout — focus confirmation calls on COD orders before you ship.",
      "Export orders or integrate with your courier workflow as your volume grows.",
    ],
  },
  {
    slug: "recover-abandoned-carts",
    title: "Recover abandoned carts",
    excerpt: "Win back buyers who left checkout without ordering.",
    categoryId: "orders-cod",
    popular: true,
    keywords: ["abandoned", "cart", "recovery"],
    body: [
      "View abandoned checkouts in Dashboard → Orders → Abandoned.",
      "See customer contact info and cart contents. Follow up via WhatsApp or phone — personal outreach works well for COD.",
      "Create a draft order from an abandoned checkout when the customer confirms by phone.",
    ],
  },
  {
    slug: "create-draft-orders",
    title: "Create manual orders",
    excerpt: "Place orders manually for phone or WhatsApp sales.",
    categoryId: "orders-cod",
    keywords: ["draft", "manual", "order"],
    body: [
      "Go to Dashboard → Orders → Create order.",
      "Search an existing customer or enter new details, add products, then Create order or Save draft.",
      "Useful for Instagram DM sales and phone orders common in Morocco.",
    ],
  },
  {
    slug: "handle-returns-and-refunds",
    title: "Handle returns and refunds",
    excerpt: "Process returned items and update inventory.",
    categoryId: "orders-cod",
    keywords: ["return", "refund", "exchange"],
    body: [
      "Open Dashboard → Orders → Returns to see return requests and process them.",
      "Update order status and restock inventory when items come back.",
      "For COD, refunds are typically handled in cash or bank transfer — document the refund in order notes.",
    ],
  },
  // Domains & hosting
  {
    slug: "connect-a-custom-domain",
    title: "Connect a custom domain",
    excerpt: "Use your own domain with automatic SSL — step by step.",
    categoryId: "domains-hosting",
    popular: true,
    keywords: [
      "domain",
      "dns",
      "ssl",
      "custom",
      "namecheap",
      "godaddy",
      "cloudflare",
    ],
    body: [
      "Open Online Store → Domains. Choose Subdomain (shop.yourbrand.com) or Root domain (yourbrand.com), enter the hostname, then Connect.",
      "Copy the DNS records Ettajer shows. For a root domain you usually need an A record (@ → 76.76.21.21) and a CNAME (www → cname.vercel-dns.com). For a subdomain you only need one CNAME. Always use the exact values on your Domains page.",
      "Log in at your registrar (Namecheap, GoDaddy, Cloudflare, Hostinger, OVH, Google Domains / Squarespace) and paste those records. Remove any old A/AAAA/CNAME that conflict with the same host.",
      "Back in Ettajer, press Check DNS. Status becomes Live when DNS and SSL are ready — often minutes, sometimes up to 48 hours.",
      "Optional: set Primary address to yourbrand.com or www.yourbrand.com so the other hostname redirects (308).",
      "Need registrar screenshots? See the Namecheap, GoDaddy, Cloudflare, Hostinger, OVH, and Google Domains tutorials in Help → Domains & hosting.",
    ],
  },
  {
    slug: "connect-domain-namecheap",
    title: "Connect your domain with Namecheap",
    excerpt: "Point Namecheap Advanced DNS to Ettajer with A and CNAME records.",
    categoryId: "domains-hosting",
    popular: true,
    keywords: ["namecheap", "dns", "domain", "advanced dns"],
    body: [
      "In Ettajer go to Online Store → Domains, connect yourbrand.com (or a subdomain), and keep the DNS table open so you can copy Host and Value exactly.",
      "Sign in at namecheap.com → Domain List → Manage next to your domain → Advanced DNS.",
      "For a root domain: add an A Record with Host @ and Value 76.76.21.21 (or the A target Ettajer shows). Add a CNAME Record with Host www and Value cname.vercel-dns.com (or Ettajer’s CNAME target). Delete conflicting Parked / Redirect / old A records for @ or www.",
      "For a subdomain like shop.yourbrand.com: add a CNAME with Host shop (the label only) and Value matching Ettajer’s CNAME target. Leave @ alone if you still use email or another site on the root.",
      "Save all changes. TTL can stay Automatic. Wait a few minutes, then in Ettajer click Check DNS until status is Live. SSL is issued automatically after DNS is correct.",
      "Tip: Namecheap email (MX) is separate — do not delete MX/TXT records unless you intend to move email.",
    ],
  },
  {
    slug: "connect-domain-godaddy",
    title: "Connect your domain with GoDaddy",
    excerpt: "Edit GoDaddy DNS records so your store goes live on Ettajer.",
    categoryId: "domains-hosting",
    keywords: ["godaddy", "dns", "domain"],
    body: [
      "Connect the domain in Ettajer Online Store → Domains and copy the A / CNAME values shown.",
      "In GoDaddy open My Products → Domains → your domain → DNS (or Manage DNS).",
      "Root domain: set an A record for @ (or Name blank) to 76.76.21.21. Set a CNAME for www to cname.vercel-dns.com. Remove GoDaddy “forwarding” or parking that overrides these hosts.",
      "Subdomain: add a CNAME for the label (e.g. shop) pointing to Ettajer’s CNAME target.",
      "Save. Propagation is often fast on GoDaddy. Return to Ettajer and Check DNS until Live.",
      "If GoDaddy asks to use their nameservers vs. custom: keep GoDaddy nameservers and only edit DNS records unless you intentionally use Cloudflare nameservers.",
    ],
  },
  {
    slug: "connect-domain-cloudflare",
    title: "Connect your domain with Cloudflare",
    excerpt: "Add DNS records in Cloudflare with proxy (orange cloud) off for SSL.",
    categoryId: "domains-hosting",
    keywords: ["cloudflare", "dns", "proxy", "ssl"],
    body: [
      "Connect your hostname in Ettajer Online Store → Domains and copy the targets.",
      "In Cloudflare open your site → DNS → Records.",
      "Root domain: A record Name @ (or yourbrand.com) → 76.76.21.21. CNAME Name www → cname.vercel-dns.com. Set Proxy status to DNS only (grey cloud) while SSL provisions — orange cloud can delay or break certificate issuance.",
      "Subdomain: CNAME Name shop → Ettajer CNAME target, also DNS only initially.",
      "Save. In Ettajer run Check DNS until Live. After HTTPS works you can optionally turn the proxy on if you understand Cloudflare SSL modes (Full / Full strict).",
      "If the domain uses Cloudflare nameservers elsewhere, edit DNS only in Cloudflare — not at the old registrar.",
    ],
  },
  {
    slug: "connect-domain-hostinger",
    title: "Connect your domain with Hostinger",
    excerpt: "Update DNS from Hostinger hPanel so Ettajer can serve your store.",
    categoryId: "domains-hosting",
    keywords: ["hostinger", "hpanel", "dns"],
    body: [
      "In Ettajer connect the domain under Online Store → Domains and note the A and CNAME values.",
      "Open Hostinger hPanel → Domains → Manage → DNS / DNS Zone Editor.",
      "Root: A record for @ → 76.76.21.21. CNAME for www → cname.vercel-dns.com. Remove Hostinger parking or old website A records that conflict.",
      "Subdomain: CNAME for the host label (shop) → Ettajer CNAME target.",
      "Save DNS. Wait a few minutes, then Check DNS in Ettajer until Live and SSL is ready.",
      "If Hostinger points the domain to a Website Builder by default, disconnect or pause that site so it does not overwrite your DNS.",
    ],
  },
  {
    slug: "connect-domain-ovh",
    title: "Connect your domain with OVHcloud",
    excerpt: "Edit the OVH DNS zone for .com, .fr, and .ma domains.",
    categoryId: "domains-hosting",
    keywords: ["ovh", "ovhcloud", "dns", ".ma"],
    body: [
      "Connect your domain in Ettajer Online Store → Domains and copy the exact record values.",
      "In the OVHcloud Control Panel go to Web Cloud → Domain names → your domain → DNS zone.",
      "Root domain: add an A record for the domain (empty subdomain / @) to 76.76.21.21. Add a CNAME for www targeting cname.vercel-dns.com (with trailing dot if OVH requires it).",
      "Subdomain: add a CNAME for the subdomain label pointing to Ettajer’s CNAME target.",
      "Delete conflicting A/AAAA/CNAME entries for the same host. Apply the DNS zone changes.",
      "Return to Ettajer and Check DNS until status is Live. SSL follows automatically after propagation.",
    ],
  },
  {
    slug: "connect-domain-google-domains",
    title: "Connect your domain with Google Domains / Squarespace",
    excerpt: "Update DNS after Google Domains moved to Squarespace Domains.",
    categoryId: "domains-hosting",
    keywords: ["google domains", "squarespace", "dns"],
    body: [
      "Former Google Domains are managed at Squarespace Domains. Connect the hostname in Ettajer Online Store → Domains first.",
      "Sign in to Squarespace Domains → your domain → DNS settings (or Advanced DNS).",
      "Root: custom A record for @ / apex → 76.76.21.21. CNAME for www → cname.vercel-dns.com (or the values Ettajer shows).",
      "Subdomain: CNAME for the host label → Ettajer CNAME target. Remove Squarespace website defaults if they conflict.",
      "Save, then Check DNS in Ettajer until Live. SSL is automatic.",
      "If your domain still shows “Google Domains” branding in email, use the migration link Squarespace sent — DNS is edited in the new console.",
    ],
  },
  {
    slug: "fix-custom-domain-not-working",
    title: "Fix custom domain not working",
    excerpt: "DNS, propagation, and SSL troubleshooting.",
    categoryId: "troubleshooting",
    popular: true,
    keywords: ["domain", "dns", "ssl", "not working"],
    body: [
      "Confirm your A or CNAME records match exactly what Ettajer shows in Online Store → Domains.",
      "DNS changes can take up to 48 hours to propagate worldwide. Use a DNS checker to verify.",
      "If SSL is pending, wait for DNS to resolve first. Contact support with your domain if issues persist after 48 hours.",
      "On Cloudflare, set records to DNS only (grey cloud) until Live. Remove parking, forwarding, and duplicate AAAA records.",
      "Follow the Namecheap, GoDaddy, Hostinger, OVH, or Google Domains tutorials if you are unsure where to edit DNS.",
    ],
  },
  {
    slug: "store-speed-and-hosting",
    title: "Store speed and hosting",
    excerpt: "Edge hosting, image optimization, and fast checkout.",
    categoryId: "domains-hosting",
    keywords: ["speed", "hosting", "cdn", "performance"],
    body: [
      "Every Ettajer storefront is served from the edge with pre-rendered pages and optimized images.",
      "You do not need separate hosting — your store, checkout, and admin run on one platform.",
      "Core Web Vitals are tuned for mobile buyers in Morocco.",
    ],
  },
  {
    slug: "ssl-https-custom-domain",
    title: "SSL and HTTPS on your custom domain",
    excerpt: "Free certificates after DNS is pointed correctly.",
    categoryId: "domains-hosting",
    keywords: ["ssl", "https", "certificate", "secure"],
    body: [
      "After you connect a domain and DNS propagates, Ettajer provisions SSL automatically — no separate certificate purchase.",
      "Open https://yourdomain.com in a private window. You should see a padlock with no certificate warnings.",
      "If HTTPS fails, re-check DNS in Dashboard → Domains (A/CNAME targets) and wait for propagation — often minutes, sometimes up to 48 hours.",
      "Always share https links in ads and WhatsApp so browsers do not warn buyers.",
      "Meta domain verification also expects your HTTPS homepage to load cleanly with the verification meta tag.",
    ],
  },
  // Billing
  {
    slug: "pricing-plans-and-trial",
    title: "Pricing plans and free trial",
    excerpt: "Start with 0 DH your first month on Growth, then monthly or annual billing.",
    categoryId: "billing",
    popular: true,
    keywords: ["pricing", "plan", "trial", "growth"],
    body: [
      "Ettajer offers Starter, Growth, and Business plans. Growth includes 0 DH for your first month.",
      "After the trial, you are billed monthly or annually. Annual billing saves roughly 20%.",
      "Upgrade or downgrade anytime from Settings → Plan.",
    ],
  },
  {
    slug: "transaction-fees-explained",
    title: "Transaction fees explained",
    excerpt: "0% platform fees on Growth and Business plans.",
    categoryId: "billing",
    keywords: ["fees", "transaction", "commission"],
    body: [
      "Ettajer charges 0% transaction fees on Growth and Business plans — that is Ettajer’s platform fee, not Stripe or PayPal’s fee.",
      "Starter includes a small Ettajer platform fee on sales. Stripe and PayPal still charge their own processing fees when customers pay online.",
      "COD orders do not incur card or PayPal processing fees (you collect cash on delivery).",
      "Online payments: money goes to your Stripe connected account or your PayPal account. See Set up online payments for connect steps.",
    ],
  },
  {
    slug: "upgrade-or-change-your-plan",
    title: "Upgrade or change your plan",
    excerpt: "Move between Starter, Growth, and Business when you are ready.",
    categoryId: "billing",
    keywords: ["upgrade", "plan", "billing", "growth", "business"],
    body: [
      "Open Settings → Plan to see your current plan and available upgrades.",
      "Growth and Business unlock higher limits, verification tools, and 0% Ettajer transaction fees.",
      "Upgrades apply immediately for new features; billing is prorated according to your subscription cycle.",
      "You can switch monthly ↔ annual later to unlock the yearly discount.",
      "Contact support before downgrading if you rely on features (extra domains, automation) that the lower plan does not include.",
    ],
  },
  // Marketing
  {
    slug: "connect-marketing-pixels",
    title: "Connect marketing pixels",
    excerpt: "Meta, Google, TikTok, and more from the marketing dashboard.",
    categoryId: "marketing",
    popular: true,
    keywords: ["pixel", "tracking", "ads", "marketing", "integrations"],
    body: [
      "Open Dashboard → Marketing → Integrations to connect Meta, Google Tag Manager, TikTok, Pinterest, and Snapchat.",
      "For Meta, use Connect with Meta to pick a pixel and save a Conversions API token automatically — or paste a Pixel ID manually.",
      "Enable the events you care about (PageView, ViewContent, AddToCart, InitiateCheckout, Purchase). Ettajer fires them on the live storefront and checkout.",
      "Open each platform setup page for Catalog feeds, Custom Audiences, Domain verification, and Event diagnostics where available.",
      "Also under Marketing: Email (campaigns and automations) and Discounts.",
      "Before you spend on ads, follow the Meta ads launch checklist. For email, follow the Email Marketing launch checklist.",
    ],
  },
  {
    slug: "connect-meta-pixel",
    title: "Connect Meta Pixel with Ettajer",
    excerpt: "Link Facebook & Instagram ads with Pixel, CAPI, and Connect with Meta.",
    categoryId: "marketing",
    popular: true,
    keywords: [
      "meta",
      "facebook",
      "instagram",
      "pixel",
      "capi",
      "conversions api",
      "oauth",
      "connect with meta",
    ],
    body: [
      "Go to Dashboard → Marketing → Integrations → Meta (or Marketing → Meta).",
      "Preferred: click Connect with Meta, log in with Facebook Login for Business, then choose the pixel to use. Ettajer saves the Pixel ID and a Conversions API access token.",
      "Alternative: paste your Pixel ID from Meta Events Manager → Data Sources → Pixels, then save.",
      "Turn tracking on and enable the events you need. Purchase uses a shared event id (purchase_{orderNumber}) so browser Pixel and server CAPI dedupe as one conversion.",
      "Optional: enable Test mode under Advanced and paste a Meta test event code to validate in Events Manager → Test events before you spend on ads.",
    ],
  },
  {
    slug: "meta-conversions-api-and-advanced-matching",
    title: "Meta Conversions API and advanced matching",
    excerpt: "Server events when cookies are blocked, with hashed email and phone.",
    categoryId: "marketing",
    popular: true,
    keywords: [
      "capi",
      "conversions api",
      "advanced matching",
      "meta",
      "dedupe",
      "event_id",
      "emq",
    ],
    body: [
      "Conversions API (CAPI) sends the same key events from Ettajer’s servers — useful when browsers block third-party cookies.",
      "Connect with Meta stores your access token automatically. Manual CAPI tokens can also be managed under Meta → Advanced when needed.",
      "InitiateCheckout and Purchase include hashed email/phone (and name/address when available) for Meta advanced matching — never send plain PII to the browser pixel payload.",
      "Browser Pixel and CAPI share the same event_id so Meta counts one conversion, not two. Purchase always uses purchase_{orderNumber}.",
      "Check Dashboard → Marketing → Meta → Diagnostics for recent CAPI sends, failures, and skips (works beyond test mode).",
    ],
  },
  {
    slug: "meta-product-catalog-feed",
    title: "Sync your product catalog to Meta",
    excerpt: "Scheduled TSV feed for Dynamic Ads and Advantage+ shopping.",
    categoryId: "marketing",
    popular: true,
    keywords: [
      "catalog",
      "feed",
      "dynamic ads",
      "advantage+",
      "meta commerce",
      "product feed",
    ],
    body: [
      "Open Marketing → Meta → Catalog. Copy the scheduled feed URL (optionally lock it with a feed key).",
      "In Meta Commerce Manager, create or select a catalog → Add data source → Scheduled feed → paste the Ettajer URL and set hourly or daily fetch.",
      "Product IDs in the feed match Pixel content_ids, so Dynamic Ads and retargeting line up with ViewContent / AddToCart / Purchase.",
      "Only active Online Store products with at least one image are included. Paste your Catalog ID back in Ettajer to track setup progress.",
      "Rotate the feed key anytime if the URL was shared widely — then update Commerce Manager with the new URL after you save.",
    ],
  },
  {
    slug: "meta-custom-audiences",
    title: "Push purchasers and abandoners to Meta audiences",
    excerpt: "Custom Audiences from your order and abandoned-checkout lists.",
    categoryId: "marketing",
    keywords: [
      "custom audiences",
      "retargeting",
      "lookalike",
      "purchasers",
      "abandoners",
      "meta ads",
    ],
    body: [
      "Open Marketing → Meta → Audiences after Connect with Meta (ads permissions required).",
      "Select the Meta ad account, then Push to Meta for Purchasers and/or Abandoners.",
      "Emails and phones are SHA-256 hashed before upload. Abandoners exclude known purchasers for cleaner retargeting.",
      "Use these lists for retargeting, lookalikes, or to exclude existing buyers from prospecting campaigns. Matching in Ads Manager can take a few hours.",
      "Re-sync anytime to replace the list with your latest customers. After the first push, enable Daily auto re-sync and save — Ettajer refreshes existing audiences overnight (needs CRON_SECRET on the server).",
    ],
  },
  {
    slug: "verify-meta-domain",
    title: "Verify your domain with Meta",
    excerpt: "Domain verification for Aggregated Event Measurement and link ownership.",
    categoryId: "marketing",
    keywords: [
      "domain verification",
      "aem",
      "aggregated event measurement",
      "facebook-domain-verification",
      "brand safety",
    ],
    body: [
      "Meta verifies a domain you own — connect a custom domain first under Dashboard → Domains (Ettajer subdomains cannot be verified as your brand domain).",
      "In Meta Business Settings → Brand safety → Domains, add your root domain (example.com, no www).",
      "Choose meta-tag verification, copy the content value, and paste it in Marketing → Meta → Domain.",
      "Save Meta settings so Ettajer injects facebook-domain-verification on your storefront homepage, then click Verify in Meta.",
      "Use Check status in Ettajer to confirm the tag is live. Keep the tag published — Meta may re-check periodically.",
      "Then open Events Manager → Aggregated Event Measurement and prioritize: Purchase → InitiateCheckout → AddToCart → ViewContent → PageView (shown on the Domain tab).",
    ],
  },
  {
    slug: "meta-event-diagnostics",
    title: "Read Meta event diagnostics",
    excerpt: "See last CAPI sends and failures beyond test mode.",
    categoryId: "marketing",
    keywords: ["diagnostics", "capi", "failed events", "test events", "meta"],
    body: [
      "Open Marketing → Meta → Diagnostics for a live log of Conversions API deliveries.",
      "Filter by Sent, Failed, or Skipped. Each row shows event name, shared event_id, source (storefront, cart, checkout), and error text when Meta rejects a call.",
      "Successful PageViews are omitted to reduce noise; PageView failures and all conversion events are kept.",
      "Pair Diagnostics with Meta Events Manager → Test events when Test mode is on under Advanced.",
      "If the log is empty, browse the live storefront, add to cart, or place a test order — then refresh Diagnostics.",
    ],
  },
  {
    slug: "connect-tiktok-pixel",
    title: "Connect TikTok Pixel",
    excerpt: "Measure TikTok ad performance and optimize campaigns.",
    categoryId: "marketing",
    keywords: ["tiktok", "pixel", "ads"],
    body: [
      "Get your Pixel ID from TikTok Ads Manager → Assets → Events → Web Events.",
      "In Ettajer Marketing → Integrations → TikTok, paste the ID and enable standard e-commerce events.",
      "TikTok works well for fashion and lifestyle brands targeting Moroccan youth.",
    ],
  },
  {
    slug: "connect-google-tag-manager",
    title: "Connect Google Tag Manager",
    excerpt: "Manage Google Ads and Analytics tags in one place.",
    categoryId: "marketing",
    keywords: ["google", "gtm", "analytics", "ads"],
    body: [
      "Create a GTM container at tagmanager.google.com and copy the Container ID (GTM-XXXX).",
      "In Ettajer Marketing → Integrations → Google or GTM, paste the ID.",
      "Configure tags inside GTM for Google Ads conversions and GA4 without editing your store code.",
    ],
  },
  {
    slug: "connect-pinterest-tag",
    title: "Connect Pinterest Tag and Conversions API",
    excerpt: "Tag + server events with shared event_id for accurate ROAS.",
    categoryId: "marketing",
    popular: true,
    keywords: ["pinterest", "tag", "ads", "capi", "conversions api"],
    body: [
      "Open Marketing → Integrations → Pinterest. Prefer Connect with Pinterest to pick a Tag and ad account, or paste Tag ID + Ad account ID manually.",
      "Under Advanced, paste a Conversion access token from Pinterest Ads (required for Conversions API — OAuth cannot replace this token).",
      "Enable Purchase and AddToCart (and other events you need). Browser Tag and server CAPI share the same event_id; Purchase uses purchase_{orderNumber}.",
      "Optional: open the Catalog tab, copy the product feed URL, and add it in Pinterest Catalogs so products become shoppable Pins.",
      "Verify with Pinterest Tag Helper and Marketing → Pinterest → Diagnostics after a live test order. Strong for home decor, fashion, and visual product categories.",
    ],
  },
  {
    slug: "pinterest-conversions-api",
    title: "Pinterest Conversions API setup",
    excerpt: "Server-side events when cookies are blocked, with email/phone matching.",
    categoryId: "marketing",
    keywords: ["pinterest", "capi", "conversions", "event_id", "dedupe"],
    body: [
      "Conversions API sends the same funnel events from Ettajer servers — useful when browsers block the Tag.",
      "You need three things: Tag ID, Ad account ID, and a Conversion access token (Advanced tab).",
      "Checkout and cart APIs send Purchase and AddToCart with hashed email/phone for better match rates on COD orders.",
      "Tag and CAPI must use the same event_id so Pinterest counts one conversion. Purchase always uses purchase_{orderNumber}.",
      "Use Diagnostics to see Sent / Failed server deliveries. Turn Test mode on while validating, then off before scaling spend.",
    ],
  },
  {
    slug: "pinterest-product-catalog",
    title: "Share products to Pinterest Catalog",
    excerpt: "Hosted TSV feed so Pinterest creates product Pins for shopping ads.",
    categoryId: "marketing",
    keywords: ["pinterest", "catalog", "feed", "product pins", "shopping"],
    body: [
      "Open Marketing → Integrations → Pinterest → Catalog. Ettajer builds a live TSV feed of active products with images.",
      "Copy the scheduled feed URL (optionally generate a feed key so only Pinterest with ?key=… can fetch it).",
      "In Pinterest Business → Catalogs, add a data source, paste the URL, choose TSV, and set your country/language.",
      "Product IDs in the feed match Tag/CAPI product_ids so shopping ads and conversion tracking stay aligned.",
      "Pinterest Catalogs must be available for your Business account region. Refresh is typically about once per day.",
    ],
  },
  {
    slug: "connect-with-pinterest",
    title: "Connect with Pinterest (OAuth)",
    excerpt: "One-click Tag + ad account selection — Conversion token still from Ads Manager.",
    categoryId: "marketing",
    keywords: ["pinterest", "oauth", "connect", "tag", "app id"],
    body: [
      "Platform admins set PINTEREST_APP_ID and PINTEREST_APP_SECRET, and register redirect URIs for localhost and production.",
      "Merchants open Marketing → Pinterest → Connect with Pinterest, approve ads:read (and catalogs:read), then pick a Tag.",
      "Ettajer saves Tag ID and Ad account ID. Add the Conversion access token under Advanced for server events — Pinterest requires that token from Ads Manager.",
      "If OAuth isn’t configured on the server, paste Tag ID and Ad account ID manually — tracking still works.",
    ],
  },
  {
    slug: "connect-snapchat-pixel",
    title: "Connect Snapchat Pixel",
    excerpt: "Attribute Snapchat ad spend to store purchases.",
    categoryId: "marketing",
    keywords: ["snapchat", "pixel", "ads"],
    body: [
      "Get your Pixel ID from Snapchat Ads Manager → Events Manager.",
      "Add it in Marketing → Integrations → Snapchat.",
      "Enable Purchase and AddToCart for full funnel tracking.",
    ],
  },
  {
    slug: "create-discounts-and-campaigns",
    title: "Create discount codes",
    excerpt: "Promo codes customers can apply at checkout.",
    categoryId: "marketing",
    popular: true,
    keywords: [
      "discount",
      "coupon",
      "promo",
      "sale",
      "percentage",
      "fixed amount",
    ],
    body: [
      "Go to Marketing → Discounts to create percentage or fixed-amount codes.",
      "Set an expiry date and usage limits so a viral Story does not drain your margin.",
      "Share codes on Instagram, WhatsApp, and email campaigns. Keep names short and easy to type on mobile.",
      "Customers apply the code at storefront checkout. Track redemptions on the Discounts page.",
      "Pair a first-order discount with Email → Automations (Newsletter signup) for a welcome offer.",
      "For paid ads, put the same promo in your creative and add UTM tags to your storefront link (utm_source, utm_medium, utm_campaign).",
    ],
  },
  {
    slug: "built-in-seo",
    title: "Built-in SEO",
    excerpt: "Sitemaps, meta tags, and clean URLs out of the box.",
    categoryId: "marketing",
    keywords: ["seo", "google", "search", "sitemap"],
    body: [
      "Every store includes server-rendered pages, XML sitemaps, canonical URLs, and Open Graph previews.",
      "Set your shop title, meta description, and keywords in Settings → SEO. Leave fields blank to use your store name and description.",
      "You can also refine titles on individual pages and products from the editor.",
    ],
  },
  {
    slug: "meta-ads-launch-checklist",
    title: "Meta ads launch checklist",
    excerpt: "Pixel, CAPI, catalog, domain, and audiences before you spend.",
    categoryId: "marketing",
    popular: true,
    keywords: ["checklist", "meta ads", "launch", "facebook ads", "instagram ads"],
    body: [
      "1. Connect Pixel + CAPI via Marketing → Meta → Connect with Meta, then enable Purchase and AddToCart.",
      "2. Run a test order with Test mode + a Meta test event code; confirm Pixel and CAPI share purchase_{orderNumber} in Diagnostics.",
      "3. Paste your Catalog feed URL into Commerce Manager and save the Catalog ID in Ettajer.",
      "4. Connect a custom domain, verify it under Meta → Domain (required for Aggregated Event Measurement on iOS).",
      "5. In Events Manager → Aggregated Event Measurement, prioritize Purchase → InitiateCheckout → AddToCart → ViewContent → PageView.",
      "6. Push Purchasers and Abandoners audiences (enable Daily auto re-sync after the first push), then build campaigns that exclude buyers or retarget abandoners.",
      "7. Turn Test mode off before scaling spend. Keep Diagnostics open the first week to catch token or permission errors early.",
    ],
  },
  {
    slug: "meta-test-events-guide",
    title: "Test Meta events before going live",
    excerpt: "Use Test mode and Events Manager without polluting production data.",
    categoryId: "marketing",
    keywords: ["test events", "test mode", "events manager", "meta", "debug"],
    body: [
      "In Marketing → Meta → Advanced, enable Test mode and paste the TEST… code from Events Manager → Test events.",
      "Open your live storefront (not builder preview). Browse a product, add to cart, start checkout with contact details, then place a small test order.",
      "In Meta Test events you should see PageView, ViewContent, AddToCart, InitiateCheckout, and Purchase — often as browser + server pairs with the same event_id.",
      "In Ettajer → Meta → Diagnostics, confirm Purchase and AddToCart show as Sent (not Failed).",
      "Disable Test mode and clear the test code before real campaigns so production events are not marked as tests.",
    ],
  },
  {
    slug: "utm-links-and-attribution",
    title: "UTM links and campaign attribution",
    excerpt: "Track Instagram, TikTok, Meta, and email traffic with tagged links.",
    categoryId: "marketing",
    popular: true,
    keywords: [
      "utm",
      "attribution",
      "campaign",
      "instagram",
      "tiktok",
      "tracking links",
      "email",
    ],
    body: [
      "Build tracked storefront links with utm_source, utm_medium, and utm_campaign on your store URL.",
      "Example: utm_source=instagram, utm_medium=social, utm_campaign=summer_sale. Share that URL in bios, Stories, and ads.",
      "For email, use utm_source=email and a campaign name that matches your Email → Campaigns send.",
      "Ettajer stores UTM values with the order so you can see which campaigns drove COD purchases.",
      "Use consistent naming (lowercase, underscores) so reports stay clean across weeks.",
      "Pair UTMs with Meta Pixel / CAPI for ad platform optimization, and with Analytics reports for your own channel mix.",
    ],
  },
  {
    slug: "newsletter-subscribers",
    title: "Email Marketing overview",
    excerpt:
      "Home, campaigns, automations, subscribers, and the rest of Email — explained simply.",
    categoryId: "marketing",
    popular: true,
    keywords: [
      "newsletter",
      "email",
      "subscribers",
      "signup",
      "template",
      "compose",
      "theme",
      "automation",
      "welcome",
      "campaign",
      "email marketing",
      "home",
    ],
    body: [
      "Open Marketing → Email. Home shows a short setup checklist, your list size, and recent sends.",
      "Primary tabs: Campaigns (one email to many people), Templates, Automations (one email when something happens), Subscribers, and Analytics.",
      "More tools: Segments (target groups), Ideas (what to send next), Email flows (multi-step journeys), Sending status, Inbox health, and Email setup.",
      "Grow your list: add a Newsletter section in the theme builder so visitors can opt in. They appear under Subscribers.",
      "Start simple: create a template → turn on a welcome automation → send your first campaign to active subscribers.",
      "Every marketing email includes your business name, store address, support email, Manage Preferences, and Unsubscribe.",
      "Respect unsubscribes — keep messaging relevant and never buy email lists.",
      "For a step-by-step path, open the Email Marketing launch checklist.",
    ],
  },
  {
    slug: "email-marketing-launch-checklist",
    title: "Email Marketing launch checklist",
    excerpt: "Go from empty list to first campaign in seven clear steps.",
    categoryId: "marketing",
    popular: true,
    keywords: [
      "email checklist",
      "launch",
      "newsletter setup",
      "first campaign",
      "tutorial",
      "guide",
    ],
    body: [
      "1. Open Marketing → Email → More → Email setup. Connect a provider (or Ettajer Managed) and confirm your from address.",
      "2. In Inbox health, add and verify your sending domain (SPF, DKIM, DMARC) so more emails reach the inbox.",
      "3. Add a Newsletter block in the theme builder and publish. Confirm a test signup appears under Subscribers.",
      "4. Create a template under Templates (gallery starter or blank). Write a clear subject, headline, body, and button.",
      "5. Turn on Automations → Newsletter signup with that template so new subscribers get a welcome email.",
      "6. Optional: create a Segment (e.g. never purchased) and turn on Abandoned cart if you sell COD.",
      "7. Open Campaigns, pick the template, send or schedule to active subscribers, then watch Sending status and Analytics.",
    ],
  },
  {
    slug: "email-campaigns-guide",
    title: "Campaigns, templates, and quick send",
    excerpt: "Design reusable emails and broadcast them to your list.",
    categoryId: "marketing",
    keywords: [
      "campaigns",
      "templates",
      "quick send",
      "schedule",
      "broadcast",
      "subject line",
      "product blocks",
    ],
    body: [
      "Templates are reusable emails. Create one under Templates, or start from a gallery starter.",
      "In the editor: pick a theme, write subject and body, set the button, and optionally add product blocks from your catalog.",
      "Use AI writing in the editor to draft subjects, improve copy, shorten, or translate — then review before saving.",
      "Campaigns send one template to many people. Choose audience filters, preview who will receive it, then send now or schedule.",
      "On Subscribers, Quick send opens a sheet for a fast one-off broadcast without building a full campaign draft.",
      "History on Campaigns shows drafts, scheduled, sending, completed, and failed sends. Open a campaign for timeline and recipients.",
      "Unsubscribed, bounced, and complained contacts are skipped automatically.",
    ],
  },
  {
    slug: "email-automations-and-flows",
    title: "Automations and email flows",
    excerpt: "Send when customers act — or build multi-step journeys.",
    categoryId: "marketing",
    keywords: [
      "automations",
      "welcome email",
      "abandoned cart",
      "purchase",
      "email flows",
      "journeys",
      "triggers",
    ],
    body: [
      "Automations send one email when something happens: Newsletter signup, Purchase, Abandoned cart, or New customer.",
      "Open Automations, pick a template for each trigger, and switch it on. Order receipts stay separate from marketing mail.",
      "Email flows (More → Email flows) are multi-step journeys with delays, conditions, and tags — use them when one email is not enough.",
      "Create a flow manually or use the AI generator to scaffold Welcome, Cart, Win-back, Post-purchase, and VIP drafts.",
      "Review draft flows before you Activate. Pause anytime from the flow editor.",
      "Ideas (More → Ideas) suggests next sends from your audience scores — use Score audience if the page is empty.",
    ],
  },
  {
    slug: "email-list-health",
    title: "Subscribers, segments, and inbox health",
    excerpt: "Grow a clean list and keep emails delivering.",
    categoryId: "marketing",
    keywords: [
      "subscribers",
      "segments",
      "deliverability",
      "inbox health",
      "sending status",
      "suppression",
      "domain",
      "spf",
      "dkim",
      "bounce",
    ],
    body: [
      "Subscribers is your list. Filter by status, export when needed, and use Quick send for a fast broadcast.",
      "Segments are dynamic groups (VIP, country, never purchased, and more). They re-evaluate when you send a campaign.",
      "Sending status shows pending, sending, sent, and failed jobs. Cancel stuck or failed retries if needed.",
      "Inbox health covers sender reputation, provider status, domain authentication, and the suppression list.",
      "Add your sending domain and verify SPF, DKIM, and DMARC. Poor authentication is a common cause of spam folder delivery.",
      "Email setup (More → Email setup, or Settings → Email) connects providers, domains, and from addresses.",
      "If bounce or complaint rates rise, pause big sends, clean inactive contacts, and fix domain auth before scaling again.",
    ],
  },
  {
    slug: "customer-messages",
    title: "Customer messages",
    excerpt: "Read and reply to storefront contact messages.",
    categoryId: "marketing",
    keywords: [
      "messages",
      "inbox",
      "contact form",
      "customer support",
      "whatsapp",
    ],
    body: [
      "Storefront contact form messages are handled from your support email — make sure Settings → Contact has a working address (and WhatsApp if you use it).",
      "Reply promptly — fast responses improve COD confirmation rates when shoppers ask about delivery or size.",
      "For order-specific questions, open the order in Orders and keep fulfillment notes there.",
      "Marketing emails are separate: use Email for campaigns; use your support channel for one-to-one shopper questions.",
    ],
  },
  {
    slug: "gift-cards-for-customers",
    title: "Sell and manage gift cards",
    excerpt: "Issue store credit customers can redeem at checkout.",
    categoryId: "marketing",
    keywords: ["gift card", "voucher", "store credit"],
    body: [
      "Open Dashboard → Gift cards to create codes with an initial balance and optional expiry.",
      "Share codes privately (WhatsApp) or sell gift cards as a product if your theme supports it.",
      "Customers redeem at checkout; remaining balance stays on the card for later orders.",
      "Disable a card immediately if it was shared by mistake or refunded.",
      "Gift cards work alongside COD — great for holidays and influencer gifting in Morocco.",
    ],
  },
  // Analytics
  {
    slug: "understand-your-analytics-dashboard",
    title: "Understand your analytics dashboard",
    excerpt: "Traffic, conversion rate, and revenue at a glance.",
    categoryId: "analytics",
    popular: true,
    keywords: ["analytics", "reports", "traffic", "conversion"],
    body: [
      "Open Dashboard → Analytics for live visitors, sessions, and conversion rate.",
      "Reports show revenue over time, top products, and traffic sources.",
      "Compare periods to see if marketing campaigns or seasonal sales are working.",
    ],
  },
  {
    slug: "track-live-store-visitors",
    title: "Track live store visitors",
    excerpt: "See who is on your store right now.",
    categoryId: "analytics",
    keywords: ["live", "visitors", "realtime"],
    body: [
      "Analytics → Live shows active sessions on your storefront in real time.",
      "Useful during flash sales or Instagram live sessions to gauge traffic spikes.",
      "Pair with UTM-tagged campaign links to connect ad clicks to live sessions.",
    ],
  },
  {
    slug: "read-traffic-and-conversion-reports",
    title: "Read traffic and conversion reports",
    excerpt: "Turn visits into insight: sources, products, and drop-offs.",
    categoryId: "analytics",
    keywords: ["reports", "conversion", "funnel", "traffic sources"],
    body: [
      "Open Analytics → Reports and pick a date range that matches your campaign (or last 7 / 30 days).",
      "Check sessions vs orders to estimate conversion rate. A spike in traffic without orders usually means ads or creatives need work — not just more budget.",
      "Top products show what to restock and what to feature on the homepage.",
      "If you use UTM links, compare campaign tags with revenue to decide which channels to scale.",
      "Export or screenshot key charts before changing your store so you can measure the impact of theme or price changes.",
    ],
  },
  // Account
  {
    slug: "reset-password-and-login",
    title: "Reset password and login",
    excerpt: "Recover access to your merchant account.",
    categoryId: "account",
    keywords: ["password", "login", "account"],
    body: [
      "On the login page, click Forgot password and enter your email.",
      "Reset links expire after 1 hour and can only be used once.",
      "After 10 failed sign-in attempts, your account locks for 15 minutes.",
      "If you signed up with Google, use Continue with Google or set a password via Forgot password.",
      "Still locked out? Contact support with the email on your account.",
    ],
  },
  {
    slug: "configure-checkout-settings",
    title: "Configure checkout settings",
    excerpt: "Payments, minimum order, COD message, and storefront contact.",
    categoryId: "getting-started",
    keywords: ["checkout", "settings", "cod", "stripe", "paypal", "seo"],
    body: [
      "Open Dashboard → Settings → Payments to enable Cash on Delivery, connect Stripe for cards, and connect PayPal. Money from Stripe/PayPal goes to your accounts — see Set up online payments.",
      "Settings → Checkout controls minimum order, checkout note, COD message, and the announcement bar.",
      "Storefront contact controls WhatsApp and whether email/phone appear in the footer. SEO controls how your shop shows in Google.",
      "If you use PayPal, set store currency to USD or EUR in Settings → Languages (PayPal does not support MAD).",
      "After saving, open your live store and place a test order (COD, and Sandbox/test for Stripe or PayPal) to confirm checkout looks right.",
    ],
  },
  {
    slug: "share-your-store-on-social",
    title: "Share your store on social media",
    excerpt: "WhatsApp, Instagram, and QR codes that send buyers to checkout.",
    categoryId: "getting-started",
    popular: true,
    keywords: ["share", "whatsapp", "instagram", "qr", "link"],
    body: [
      "Copy your store URL from the dashboard or Online Store. Use a custom domain when you have one — it looks more trustworthy in ads.",
      "Share on WhatsApp Status and Instagram bio with a short offer (free shipping, COD available).",
      "Generate a QR image for packaging, pop-ups, or print flyers so offline buyers reach your catalog instantly.",
      "For paid posts, add UTM tags (utm_source, utm_medium, utm_campaign) before you paste the link.",
      "Always test the link on mobile: most Moroccan customers will open it from Instagram or WhatsApp.",
    ],
  },
  {
    slug: "manage-customers",
    title: "Manage customers",
    excerpt: "View profiles, order history, and contact info.",
    categoryId: "account",
    keywords: ["customers", "crm", "profiles"],
    body: [
      "Dashboard → Customers lists everyone who ordered or signed up on your store.",
      "Open a customer to see order history, total spend, and contact details.",
      "Export customer lists for email campaigns or WhatsApp broadcasts (respect opt-in rules).",
    ],
  },
  {
    slug: "change-store-name-currency-language",
    title: "Change store name, currency, and language",
    excerpt: "Match your brand, MAD pricing, and FR/AR/EN storefront.",
    categoryId: "account",
    keywords: ["currency", "language", "store name", "mad", "arabic", "french"],
    body: [
      "Open Settings → General to update store name, contact details, and logo.",
      "Set currency in Settings → Languages (e.g. MAD for local COD). Prices and checkout totals use this currency.",
      "PayPal checkout requires a PayPal-supported currency such as USD or EUR — not MAD. Switch currency before connecting PayPal in Settings → Payments.",
      "Choose storefront language (English, French, or Arabic). Arabic storefronts use right-to-left layout automatically.",
      "Save and open your live store URL in a private window to confirm the changes.",
      "Currency changes do not convert historical order totals — past orders keep the amounts recorded at purchase time.",
    ],
  },
  // Migration
  {
    slug: "migrate-from-shopify",
    title: "Migrate from Shopify",
    excerpt: "Import products, customers, and orders with the migration assistant.",
    categoryId: "migration",
    popular: true,
    keywords: ["shopify", "migrate", "import"],
    body: [
      "Open Dashboard → Settings → Migration and connect your Shopify store via API or upload a product CSV.",
      "We import products with images, variants, and descriptions. URL redirects can preserve SEO.",
      "For large catalogs, our team can assist on Business plans.",
    ],
  },
  {
    slug: "migrate-from-woocommerce",
    title: "Migrate from WooCommerce",
    excerpt: "Bring your catalog over with CSV import.",
    categoryId: "migration",
    keywords: ["woocommerce", "wordpress", "migrate"],
    body: [
      "Export products from WooCommerce as CSV, then import via Dashboard → Products → Import.",
      "Map columns to Ettajer fields and review a preview before confirming.",
      "Rebuild your storefront in the visual builder — typically less than a day.",
    ],
  },
  // Troubleshooting
  {
    slug: "store-not-loading",
    title: "Store not loading or blank page",
    excerpt: "Fix white screens and connection errors.",
    categoryId: "troubleshooting",
    popular: true,
    keywords: ["blank", "loading", "error", "down"],
    body: [
      "Clear your browser cache and try an incognito window. Check if the issue is only on your device or for all visitors.",
      "If you recently changed DNS, wait up to 48 hours for propagation.",
      "Ensure your store is published in Themes. Draft-only changes do not affect the live URL.",
      "Contact support if the store is down for all visitors for more than 30 minutes.",
    ],
  },
  {
    slug: "pixel-not-firing",
    title: "Marketing pixel not firing",
    excerpt: "Verify Meta, TikTok, or Google tracking is working.",
    categoryId: "troubleshooting",
    popular: true,
    keywords: ["pixel", "tracking", "not working", "meta", "capi", "diagnostics"],
    body: [
      "Confirm the Pixel ID is correct in Marketing → Integrations (or Meta → Connection) with no extra spaces.",
      "For Meta: use Connect with Meta so Pixel + Conversions API are both active. Check Marketing → Meta → Diagnostics for failed or skipped server events.",
      "Disable ad blockers when testing. Use Meta Events Manager → Test events with Test mode enabled under Meta → Advanced.",
      "Events fire on the live storefront — preview mode in the builder may not trigger pixels. Purchase dedupes with purchase_{orderNumber} across Pixel and CAPI.",
      "Allow up to 24 hours for ad platforms to show aggregate data after first install.",
    ],
  },
  {
    slug: "meta-connect-login-errors",
    title: "Fix Meta Connect login errors",
    excerpt: "Invalid scopes, missing config ID, and expired sessions.",
    categoryId: "troubleshooting",
    popular: true,
    keywords: ["oauth", "invalid scopes", "connect with meta", "login", "config_id"],
    body: [
      "Ettajer uses Facebook Login for Business with a configuration ID — do not pass classic ads_* scopes in the URL (Meta returns Invalid Scopes).",
      "Ensure META_APP_ID, META_APP_SECRET, and META_LOGIN_CONFIG_ID are set for your deployment, then restart the server after changes.",
      "In Meta App Dashboard, create a Business app → Facebook Login for Business → Configurations with ads and business permissions, then paste that Configuration ID into env.",
      "Add the OAuth redirect URI (local: http://localhost:3000/api/marketing/meta/oauth/callback, production: your live domain callback).",
      "If the pixel picker says login expired, click Connect with Meta again. For data deletion requirements, use the public /data-deletion page and callback listed in your Meta app settings.",
    ],
  },
  {
    slug: "checkout-not-completing",
    title: "Checkout not completing",
    excerpt: "When buyers cannot place COD, card, or PayPal orders.",
    categoryId: "troubleshooting",
    keywords: ["checkout", "error", "cod", "stripe", "paypal", "payment", "stuck"],
    body: [
      "Confirm at least one method is enabled in Settings → Payments: COD or PayPal (Verify & connect succeeded). Stripe cards are not activatable yet (~2 months).",
      "Required address fields must be filled — city and phone formats matter for Moroccan COD and shipping zones.",
      "If a minimum order amount is set, small carts will be blocked until the buyer adds more items.",
      "Stripe: card checkout is coming in about 2 months. Until then cards will not appear at checkout — use COD or PayPal.",
      "PayPal: mode (Sandbox vs Live) must match your Client ID/Secret. Store currency must be supported (USD/EUR — not MAD). Re-run Verify & connect after fixing currency.",
      "Ask the buyer to retry on mobile data without ad blockers; some extensions break checkout scripts.",
      "Check Dashboard → Orders → Abandoned for partial checkouts, and Meta → Diagnostics if you expected a Purchase event that never arrived.",
    ],
  },
  {
    slug: "orders-not-appearing",
    title: "Orders not appearing in dashboard",
    excerpt: "When checkout succeeds but orders are missing.",
    categoryId: "troubleshooting",
    keywords: ["orders", "missing", "checkout"],
    body: [
      "Refresh Dashboard → Orders. Check filters — you may be viewing a date range that excludes new orders.",
      "Confirm the customer completed checkout (not just added to cart).",
      "If payment or verification failed, the order may be in Abandoned instead of Orders.",
      "Contact support with the customer phone number and approximate order time.",
    ],
  },
  {
    slug: "images-not-uploading",
    title: "Images not uploading",
    excerpt: "Fix product or section image upload failures.",
    categoryId: "troubleshooting",
    keywords: ["image", "upload", "photo", "pdf", "ebook", "digital"],
    body: [
      "Use JPG, PNG, or WebP under 10 MB per file for covers and photos.",
      "For ebooks: set product type to Digital, upload Front cover + Back cover photos, then upload the PDF under Ebook file.",
      "PDF files can be up to 50 MB. Only PDF is accepted for digital downloads.",
      "Product photos upload to cloud storage — if upload fails, wait a minute and try again.",
      "Check your internet connection — large files on slow mobile networks may timeout.",
      "Try a different browser. Disable VPN if uploads consistently fail.",
      "Contact support if a specific file fails repeatedly after resizing.",
    ],
  },
];

export function getCategoryById(id: string): HelpCategory | undefined {
  return HELP_CATEGORIES.find((category) => category.id === id);
}

export function getArticleBySlug(slug: string): HelpArticle | undefined {
  return HELP_ARTICLES.find((article) => article.slug === slug);
}

export function getArticlesByCategory(categoryId: string): HelpArticle[] {
  return HELP_ARTICLES.filter((article) => article.categoryId === categoryId);
}

export function getPopularArticles(): HelpArticle[] {
  return HELP_ARTICLES.filter((article) => article.popular);
}

export function searchArticles(query: string, limit = 50): HelpArticle[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [];

  const terms = normalized.split(/\s+/).filter(Boolean);

  const scored = HELP_ARTICLES.map((article) => {
    const category = getCategoryById(article.categoryId);
    const title = article.title.toLowerCase();
    const excerpt = article.excerpt.toLowerCase();
    const keywords = (article.keywords ?? []).join(" ").toLowerCase();
    const body = article.body.join(" ").toLowerCase();
    const categoryTitle = (category?.title ?? "").toLowerCase();
    const haystack = `${title} ${excerpt} ${keywords} ${body} ${categoryTitle}`;

    let score = 0;
    for (const term of terms) {
      if (title.includes(term)) score += 10;
      if (keywords.includes(term)) score += 6;
      if (excerpt.includes(term)) score += 4;
      if (categoryTitle.includes(term)) score += 3;
      if (body.includes(term)) score += 1;
    }

    return { article, score };
  })
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((item) => item.article);

  return scored;
}

export function getSearchSuggestions(query: string, limit = 6): HelpArticle[] {
  return searchArticles(query, limit);
}
